# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='height',
            new_name='the_height',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='length',
            new_name='the_length',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weight',
            new_name='the_weight',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='width',
            new_name='the_width',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_location),
        ),
    ]
