# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank='true', default='default text', max_length=120, null='true'),
        ),
    ]
